Diversion: Remove tight coupling of all Action and Condition classes
pwr-Solaar/Solaar pull request #2740
Opened 2024-12-31 17:45 UTC by MattHag

Get rid of RuleComponent and its inheritance tree.

2025-01-02 13:21 UTC, pfps requested changes
The return of all rule functions needs to be preserved and I don't think these changes do that.   The return is used to determine whether to continue processing or terminate the current rule or all rules.

When I run with this PR only the first rule appears to be evaluated and maybe only the first condition of the first rule.

2025-01-02 13:43 UTC, MattHag commented
I reverted the logic back to check-then-act, instead of try/raise. I am not aware of any other substantial change.

2025-01-02 14:16 UTC, pfps requested changes
Better, but it looks as if only the first rule is evaluated, even if it doesn't do anything.


Before PR

```
Depress Host Switch Channel 2
2025-01-02 09:11:00,565,565    DEBUG [SolaarListener:hidraw3] logitech_receiver.base: (15) => r[11 03 0B00 00D20000000000000000000000000000]
2025-01-02 09:11:00,566,566    DEBUG [SolaarListener:hidraw3] logitech_receiver.notifications: <Device(3,4066,Craft Advanced Keyboard,112C46EA)>: notification for feature REPROG CONTROLS V4, report 0, data 00D20000000000000000000000000000
2025-01-02 09:11:00,566,566    DEBUG [SolaarListener:hidraw3] logitech_receiver.notifications: <Device(3,4066,Craft Advanced Keyboard,112C46EA)>: diverted controls pressed: 0xd2, 0x0, 0x0, 0x0
2025-01-02 09:11:00,567,567    DEBUG [MainThread] logitech_receiver.diversion: evaluating rules on Notification(11,3,0B,00,00D20000000000000000000000000000)
2025-01-02 09:11:00,568,568    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[Rule(/home/pfps/.config/solaar/rules.yaml)[Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 2 (released), Rule[Active: 198E3EB8, Set: 43DAF041 change-host 0, Set: 198E3EB8 change-host 0, Execute: notify-send Switched keyboard and mouse to receiver], Execute: notify-send Mouse not active, Set: 43DAF041 change-host 0, Execute: notify-send Switched keyboard to receiver. Mouse not active it will have to be switched manually], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 3 (released), Set: 43DAF041 change-host 2, Set: 198E3EB8 change-host 2, Execute: notify-send Switched to Bluetooth], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Lock PC (pressed), Execute: xflock4, Execute: notify-send Lock], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Show Desktop (pressed), KeyPress: Alt_L F5 click, Execute: notify-send Show Desktop], Rule(/home/pfps/.config/solaar/rules.yaml)[Feature: CROWN, Process: quodlibet, Rule[Test: crown_pressed, Test: crown_right_ratchet, KeyPress: XF86_AudioNext click, Execute: notify-send Next Song], Rule[Test: crown_pressed, Test: crown_left_ratchet, KeyPress: XF86_AudioPrev click, Execute: notify-send Previous Song], Rule[Test: crown_right_ratchet, KeyPress: XF86_AudioRaiseVolume click], Rule[Test: crown_left_ratchet, KeyPress: XF86_AudioLowerVolume click]]], Rule[Rule[Rule[Key: Brightness Down (pressed), KeyPress: XF86_MonBrightnessDown click], Rule[Key: Brightness Up (pressed), KeyPress: XF86_MonBrightnessUp click]]]]
2025-01-02 09:11:00,568,568    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 2 (released), Rule[Active: 198E3EB8, Set: 43DAF041 change-host 0, Set: 198E3EB8 change-host 0, Execute: notify-send Switched keyboard and mouse to receiver], Execute: notify-send Mouse not active, Set: 43DAF041 change-host 0, Execute: notify-send Switched keyboard to receiver. Mouse not active it will have to be switched manually], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 3 (released), Set: 43DAF041 change-host 2, Set: 198E3EB8 change-host 2, Execute: notify-send Switched to Bluetooth], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Lock PC (pressed), Execute: xflock4, Execute: notify-send Lock], Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Show Desktop (pressed), KeyPress: Alt_L F5 click, Execute: notify-send Show Desktop], Rule(/home/pfps/.config/solaar/rules.yaml)[Feature: CROWN, Process: quodlibet, Rule[Test: crown_pressed, Test: crown_right_ratchet, KeyPress: XF86_AudioNext click, Execute: notify-send Next Song], Rule[Test: crown_pressed, Test: crown_left_ratchet, KeyPress: XF86_AudioPrev click, Execute: notify-send Previous Song], Rule[Test: crown_right_ratchet, KeyPress: XF86_AudioRaiseVolume click], Rule[Test: crown_left_ratchet, KeyPress: XF86_AudioLowerVolume click]]]
2025-01-02 09:11:00,569,569    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 2 (released), Rule[Active: 198E3EB8, Set: 43DAF041 change-host 0, Set: 198E3EB8 change-host 0, Execute: notify-send Switched keyboard and mouse to receiver], Execute: notify-send Mouse not active, Set: 43DAF041 change-host 0, Execute: notify-send Switched keyboard to receiver. Mouse not active it will have to be switched manually]
2025-01-02 09:11:00,569,569    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Host Switch Channel 2 (released)
2025-01-02 09:11:00,569,569    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Host Switch Channel 3 (released), Set: 43DAF041 change-host 2, Set: 198E3EB8 change-host 2, Execute: notify-send Switched to Bluetooth]
2025-01-02 09:11:00,570,570    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Host Switch Channel 3 (released)
2025-01-02 09:11:00,570,570    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Lock PC (pressed), Execute: xflock4, Execute: notify-send Lock]
2025-01-02 09:11:00,570,570    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Lock PC (pressed)
2025-01-02 09:11:00,570,570    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Key: Show Desktop (pressed), KeyPress: Alt_L F5 click, Execute: notify-send Show Desktop]
2025-01-02 09:11:00,570,570    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Show Desktop (pressed)
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule(/home/pfps/.config/solaar/rules.yaml)[Feature: CROWN, Process: quodlibet, Rule[Test: crown_pressed, Test: crown_right_ratchet, KeyPress: XF86_AudioNext click, Execute: notify-send Next Song], Rule[Test: crown_pressed, Test: crown_left_ratchet, KeyPress: XF86_AudioPrev click, Execute: notify-send Previous Song], Rule[Test: crown_right_ratchet, KeyPress: XF86_AudioRaiseVolume click], Rule[Test: crown_left_ratchet, KeyPress: XF86_AudioLowerVolume click]]
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Feature: CROWN
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[Rule[Rule[Key: Brightness Down (pressed), KeyPress: XF86_MonBrightnessDown click], Rule[Key: Brightness Up (pressed), KeyPress: XF86_MonBrightnessUp click]]]
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[Rule[Key: Brightness Down (pressed), KeyPress: XF86_MonBrightnessDown click], Rule[Key: Brightness Up (pressed), KeyPress: XF86_MonBrightnessUp click]]
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[Key: Brightness Down (pressed), KeyPress: XF86_MonBrightnessDown click]
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Brightness Down (pressed)
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate rule: Rule[Key: Brightness Up (pressed), KeyPress: XF86_MonBrightnessUp click]
2025-01-02 09:11:00,571,571    DEBUG [MainThread] logitech_receiver.diversion: evaluate condition: Key: Brightness Up (pressed)

Release Host Switch Channel 2
2025-01-02 09:11:08,089,089    DEBUG [SolaarListener:hidraw3] logitech_receiver.base: (15) => r[11 03 0B00 00000000000000000000000000000000]
2025-01-02 09:11:08,090,090    DEBUG [SolaarListener:hidraw3] logitech_receiver.notifications: <Device(3,4066,Craft Advanced Keyboard,112C46EA)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
2025-01-02 09:11:08,090,090    DEBUG [SolaarListener:hidraw3] logitech_receiver.notifications: <Device(3,4066,Craft Advanced Keyboard,112C46EA)>: diverted controls pressed: 0x0, 0x0 [...]

2025-01-29 13:42 UTC, pfps commented
@MattHag Any action on this PR?  Are there other PRs that can be merged?

2025-01-29 14:36 UTC, MattHag commented
No, that's in hold. It needs a few more tests. But it's quite an improvement to the tight coupling. Anyone can improve my drastically, I'm busy currently

2026-06-27 11:04 UTC, closed without merging